---
- name: Prepare
  hosts: all

  roles:
    - role: geerlingguy.repo-epel
      become: True

    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: pip
          - name: boto3
        pip_executable: pip3
        pip_package: python3-pip
        working_dir: /tmp/s3
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "8"

    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: pip
            version: "20.3.4"
          - name: boto3
        pip_executable: pip
        pip_package: python-pip
        working_dir: /tmp/s3
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"
  tasks:
    - name: Create directory for creating test text file
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/test_file"
        state: directory
        mode: '0777'
        owner: "{{ lookup('env', 'HOME') | replace('/home/', '') }}"
        group: "{{ lookup('env', 'HOME') | replace('/home/', '') }}"
      delegate_to: localhost

    - name: Create test text file
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'HOME') }}/test_file/{{ item.local_file_name }}"
        content: |
          {{ item.test_string }}
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index

    - name: Simple PUT operation. AWS credentials are passed from environment variables.
      amazon.aws.aws_s3:
        aws_access_key: '{{ item.aws_access_key_id }}'
        aws_secret_key: '{{ item.aws_secret_access_key }}'
        bucket: '{{ item.s3_bucket }}'
        mode: put
        object: '{{ item.s3_object_name }}'
        security_token: '{{ item.aws_security_token }}'
        src: "{{ lookup('env', 'HOME') }}/test_file/{{ item.local_file_name }}"
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
