---
- name: Prepare
  hosts: all

  roles:
    - role: mamono210.aws_bootstrap
      become: True

  tasks:
    - name: Create directory for creating test text file
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/test_file"
        state: directory
        mode: '0777'
        owner: "{{ lookup('env', 'HOME') | replace('/home/', '') }}"
        group: "{{ lookup('env', 'HOME') | replace('/home/', '') }}"
      delegate_to: localhost

    - name: Create test text file
      ansible.builtin.template:
        src: source.template
        dest: "{{ lookup('env', 'HOME') }}/test_file/{{ item.local_file_name }}"
        mode: '0777'
        owner: "{{ lookup('env', 'HOME') | replace('/home/', '') }}"
        group: "{{ lookup('env', 'HOME') | replace('/home/', '') }}"
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index

    - name: Simple PUT operation. AWS credentials are passed from environment variables.
      amazon.aws.s3_object:
        aws_access_key: '{{ item.aws_access_key_id }}'
        aws_secret_key: '{{ item.aws_secret_access_key }}'
        bucket: '{{ item.s3_bucket }}'
        mode: put
        object: '{{ item.s3_object_name }}'
        security_token: '{{ item.aws_security_token }}'
        src: "{{ lookup('env', 'HOME') }}/test_file/{{ item.local_file_name }}"
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
